### PR TITLE
detect system php and preferred SAPI

### PR DESCRIPTION
**Pull request by kevinpapst**
Ok, this is just another "I don't know what the heck I am doing, but `Hey! It works ..." PR 😁 just kidding, but:

Bildschirmfoto 2020-08-27 um 20 08 08

- Added logic to detect system php: for now the first found binary in the PATH is used for that - I guess thats how a shell finds an executable as well: by looking through the path and using the first one that is available
- Added a column to mark/display the "system binary" in the list command
- Added a method to detect preferred SAPI and use it in server:start (order: fpm, cgi, cli, panic)

With this change I am finally able to see a working page!
Bonus points for: I could even open my Symfony project with it. Rather slow by now (probably becuase of the response buffering vs streaming issue?) ... but hey: not it works for me 🎉

### CODE REVIEW

**Review by Pierstoval — APPROVED** [review]
This is perfect! We will indeed need another way of determining the "system" executable with a better method, but for now it works and this is really good news 😁😁

🚀

**Comment by kevinpapst** [comment]
I am a fan of: step-by-step improvements to gather feedback from users in between.

We could use a `which php` as well to determine it. Not sure if that is more reliable. At least it wouldn't depend on the order of calls to `merge_binaries`.

**Comment by Pierstoval** [comment]
Totally agree for small improvements! That's what's driving me these days, and it works perfectly :smile: 

For PHP, I think executing `php --version` in a subprocess is fairly enough, because we already have a way to determine the version (via a regex), so we could just reuse it and loop on all resolved binaries and flag the detected version as `system`. WDYT?

**Comment by kevinpapst** [comment]
Sounds good. 

Where would you do that: in `current()` or in `all()` or somewhere else?

I tend to say in `current()` to make sure it is always detected at start, so no potential cache interferes with env changes.

**Comment by Pierstoval** [comment]
Nope, not in `current()`, because we must consider `system` and "current version" different: system is what you get when doing `php --version`, it'll be checked from PATH by the system. The `current` will be customizable via a `.php-version` file :)

**Comment by kevinpapst** [comment]
Aha, thanks for the explanation. I was mislead by the cache you added. 

So: as last call in `all()` or do you have another place in mind?

**Comment by Pierstoval** [comment]
Yep, just after the `merge_binaries()` calls, and before returning the list 😄

**Comment by kevinpapst** [comment]
Ok. When I find some time (customers are waiting) I will look into it.

In the meantime and if you have some free time, you could think about the auto-port PR.
I think it is an important feature to scan for free ports (if the requested/default one is blocked), I am just not sure about the implementation details. Please see it as discussion and not so much as "request for merge". I don't mind critical feedback or even closing if you want to do it differently.

**Comment by Pierstoval** [comment]
Yep, was about to check it out on my machine and continue the work on it 😉

**Pull request merged**
